version: "3.8"
services:
  mongodb:
    image : mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongodb:27017/
  # stripe:
  #   image : stripe/stripe-cli:latest
  #   volumes:
  #     - ./.stripe:/root/.config/stripe
    # command: listen --api-key sk_test_51JRB2gEwfPm4lLW0bXuety3Vof2yayqhZd4CoZHIwVls6w44ri9nRdX3GKYi7KHMbQKD1JgLBltpK3peNYEQzFBp00HzBqTolw \
    #           --device-name ${STRIPE_DEVICE_NAME} \
    #           --forward-to next-app:3000/api/webhook
