version: '3.4'

services:
  proj.sample:
    image: ${DOCKER_REGISTRY-}projsample
    build:
      context: .
      dockerfile: proj.sample/Dockerfile
  #proj.db:
  #  image: postgres:latest
  #  container_name: Database
  #  environment:
  #    - POSTGRES_DB=projsample-db
  #    - POSTGRES_USER=postgres
  #    - POSTGRES_PASSWORD=postgres
  #  volumes:
  #    - ./.containers/database:/var/lib/postgresql/data
  #  ports:
  #    - 5432:5432