
GET https://ticketing.hugo2908-02-ticking-auth.com/api/users/currentuser
Content-Type: application/json

### Test: signup sucessfull
POST https://ticketing.hugo2908-02-ticking-auth.com/api/users/signup HTTP/1.1
Content-Type: application/json

{
    "email": "abc@abc.com",
    "password": "abc_pw"
}


### Test: signup throw email validation error
POST https://ticketing.hugo2908-02-ticking-auth.com/api/users/signup HTTP/1.1
Content-Type: application/json

{
    "email": "abcabac",
    "password": "abc_pw"
}

### Test: signin throw password validation error
POST https://ticketing.hugo2908-02-ticking-auth.com/api/users/signin HTTP/1.1
Content-Type: application/json

{
    "email": "abc@abc.com",
    "password": ""
}

### Test: signin successfully
POST https://ticketing.hugo2908-02-ticking-auth.com/api/users/signin HTTP/1.1
Content-Type: application/json

{
    "email": "abc@abc.com",
    "password": "abc_pw"
}

### Test: currentuser
GET  https://ticketing.hugo2908-02-ticking-auth.com/api/users/currentuser HTTP/1.1
Content-Type: application/json
Cookie: express:sess=eyJqd3QiOiJleUpoYkdjaU9pSklVekkxTmlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKcFpDSTZJall4TVdFM1kySTRPVEUyWmpZMk1EQXhZbUUwWm1NMVlpSXNJbVZ0WVdsc0lqb2lZV0pqUUdGaVl5NWpiMjBpTENKcFlYUWlPakUyTWpreE1qVTRNVFo5Lk5iQjRBczNyQWlNYnV4cDA5VEJweDR0SHgwbFYzTzRwSkltWkNIejRNVWMifQ==;

{
    "email": "abc@abc.com",
    "password": "abc_pw"
}

###

### Test: signout
POST   https://ticketing.hugo2908-02-ticking-auth.com/api/users/signout HTTP/1.1
Content-Type: application/json

###

### Create ticket
POST   https://ticketing.hugo2908-02-ticking-auth.com/api/tickets HTTP/1.1
Cookie: express:sess=eyJqd3QiOiJleUpoYkdjaU9pSklVekkxTmlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKcFpDSTZJall4TVdFM1kySTRPVEUyWmpZMk1EQXhZbUUwWm1NMVlpSXNJbVZ0WVdsc0lqb2lZV0pqUUdGaVl5NWpiMjBpTENKcFlYUWlPakUyTWpreE1qVTRNVFo5Lk5iQjRBczNyQWlNYnV4cDA5VEJweDR0SHgwbFYzTzRwSkltWkNIejRNVWMifQ==;
Content-Type: application/json

{
    "title": "NEW CONCERT",
    "price": 500
}

###

### Update ticket
PUT    https://ticketing.hugo2908-02-ticking-auth.com/api/tickets/611e81e7192b5a001ab37dd6 HTTP/1.1
Cookie: express:sess=eyJqd3QiOiJleUpoYkdjaU9pSklVekkxTmlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKcFpDSTZJall4TVdFM1kySTRPVEUyWmpZMk1EQXhZbUUwWm1NMVlpSXNJbVZ0WVdsc0lqb2lZV0pqUUdGaVl5NWpiMjBpTENKcFlYUWlPakUyTWpreE1qVTRNVFo5Lk5iQjRBczNyQWlNYnV4cDA5VEJweDR0SHgwbFYzTzRwSkltWkNIejRNVWMifQ==;
Content-Type: application/json

{
    "title": "NEW CONCERT",
    "price": 10
}

###

### Create Order
POST     https://ticketing.hugo2908-02-ticking-auth.com/api/orders HTTP/1.1
Cookie: express:sess=eyJqd3QiOiJleUpoYkdjaU9pSklVekkxTmlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKcFpDSTZJall4TVdFM1kySTRPVEUyWmpZMk1EQXhZbUUwWm1NMVlpSXNJbVZ0WVdsc0lqb2lZV0pqUUdGaVl5NWpiMjBpTENKcFlYUWlPakUyTWpreE1qVTRNVFo5Lk5iQjRBczNyQWlNYnV4cDA5VEJweDR0SHgwbFYzTzRwSkltWkNIejRNVWMifQ==;
Content-Type: application/json

{
    "ticketId": "61210a65e902b4001ae7e2bf"
}

###