name: design-patterns/course04-modular-monolith-architecture/evently:Build

on:
  push:
    branches:
      - main
    paths:
      - 'design-patterns/course04-modular-monolith-architecture/evently/**'

env:
  DOTNET_VERSION: "8.x"

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: design-patterns/course04-modular-monolith-architecture/evently
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Restore
        run: dotnet restore Evently.sln

      - name: Build
        run: dotnet build Evently.sln --configuration Release --no-restore
        
      - name: Test
        run: dotnet test Evently.sln --configuration Release --no-restore --no-build
        
      - name: Publish
        run: dotnet publish Evently.sln --configuration Release --no-restore --no-build