name: microservice/02-ticking-app/deploy-init

env:
  CLUSTER_NAME: test-sa-ticking
  CLUSTER_RESOURCE_GROUP: hugo.group
  # NAMESPACE: {namespace-name}
  # SECRET: {secret-name}
  # APP_NAME: {app-name}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Set the target Azure Kubernetes Service (AKS) cluster. 
      - uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
      - run: kubectl create secret generic jwt-secret --from-literal=JWT_KEY=secret
      - run: kubectl create secret generic stripe-secret --from-literal STRIPE_KEY=$STRIPE_KEY
        env:
          STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
