name: microservice/02-ticking-app/deploy-tickets

on:
  push:
    branches:
      # - master
      - microservices/02-ticketing-app
    paths:
      - 'microservices/02-ticking/tickets/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - run: cd microservices/02-ticking/tickets && docker build -t hugo2908/02-ticking-tickets .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push hugo2908/02-ticking-tickets
      # Connect to digitalocean
      #- uses: digitalocean/action-doctl@v2
      #  with:
      #    tokent: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      #- run: doctl kubernetes cluster kubeconfig save ticketing

      # Connect to Azure Kubernetes Service (AKS) cluster. 
      - uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}

      #- run: kubectl rollout restart deployment tickets-depl