name: nextjs/01-bookit

on:
  push:
    branches:
      - main
    paths:
      - 'nextjs/01-bookit/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd nextjs/01-bookit && docker build -t hugo2908/nextjs-01-bookit .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push hugo2908/nextjs-01-bookit
